- Cross-Save has been implemented. It is now possible to exchange saved data between different platforms.
- Certain item types can now be used from the item request window.
- Added option to cancel XP counters on the victory screen.
- The savant now offers two methods for exchanging Rainbow Pearls,
allowing you to increase your stats in single and multiple units.
- Improved handling for left stick, reducing the chance of moving in unintended directions during battle. 
- After entering a character name, the name can be reviewed and adjusted.
- Several minor improvements have been added.
- Several additional bugs fixed.