Improvements:
• Input is more correctly filtered to prevent unintentional outfielder jumps/dives
• Added preview images in stadium selection
• Minor particle effect improvements
• Improved dirt textures in some stadiums
• Reduced animation artifacts in crowd

Bugs Addressed:
• Input can be ignored when multiple users attempt to use advanced Ego widgets simultaneously
• Baserunner incorrectly advancing after release of return-all command
• Baserunners can be incorrectly ruled safe immediately after being tagged out
• Apple Field incorrectly referred to as Apple Bowl in pre-game options
• Coaches boxes are backwards in all stadiums
• Front end menu runs slow after quitting a game during slow-motion sequence
• Newly substituted pitcher occasionally fails to throw a pitch
• Game fails to make correct ruling on balls bouncing out-of-play in foul territory
• Customizing players can inadvertently change pitcher/batter animations
• Occasional crashes during post-game fireworks
