[Ver. 1.02 - Update Details]
The following issues have been fixed.
- The player can become unable to land attacks after repeatedly performing
  interim saves and resuming them for the scenario, Battle at the Fields of Chandigarh.
- While playing with two players,
  performing a Mardān Rush would cause the other player to receive damage and warp to different locations.
- Daryun's DLC weapon, Serican Bow, has a spear icon.
- Several other minor issues have also been fixed.
