Tilgang til online-funksjoner er fjernet.
Du kan fremdeles gå online med gratisversjonen av SingStar®
som du finner på XMB™-menyen og i PlayStation®Store.
Alt av diskinnhold og -funksjoner nedenfor er allerede tilgjengelig via gratisversjonen av SingStar™:
- Tilgang til SingStore™
- Nedlasting av tidligere kjøpt innhold (deriblant sangtillegg)
- Opplasting av bilder og avspilling av video
- Se og ranger opplastet medieinnhold
