『Ragnarok Odyssey ACE』
Ver 1.01

The following issues have been fixed:
・The error regarding the Emperium Shard has been fixed.
・The problem regarding the incorrect number of Prismatic Dust dropped after defeating the Domovoi Ranger has been fixed.
・Behaviors of control type 2 and 4 on “Cancel Lock on” has been fixed true to
Ver 1.31 of Ragnarok Odyssey ACE PlayStation®Vita system.
・Other errors have been fixed. 

