- Version 1.11:
  
- A color cycling effect has been added to Bonus+ battles,
  so they can be recognized easier. The same applies to other
  global battle effects. (Speed+, Defense+, Strength+, Luck+)
- A new notification has been added that reminds players that
  grinding is not required if they focus on Bonus+ battles
  instead of random or optional battles.
- Help notifications are spawned with a much lower frequency.
- A very rare UI related crash bug has been fixed.
- A very rare battle related crash bug has been fixed.
