Compatibilidad con sistema PlayStation®Vita TV.
Compatibilidad con los nuevos packs de contenido descargable.
Nuevas evaluaciones del doctor Terapeuta para compararte con tus amigos.
Muestra qué amigos visitaron tu planeta natal.
Detección de gestos mejorada.
Se corrigió un error que impedía el desbloqueo de Robodachi.
El sonido está mejor sincronizado con las burbujas de imágenes.
Se corrigieron y optimizaron otros problemas.