Adicionado suporte ao sistema PlayStation®Vita TV
Adicionado suporte para novos pacotes de conteúdo para download
Novas avaliações de amigos com o Dr. Terapeuta comparam você com seus amigos
Veja os amigos que visitaram seu planeta natal
Detecção do gesto círculo melhorada
Corrigido problema impedindo o desbloqueio de Robodachi
Áudio está em melhor sincronia com os balões
Várias outras correções de bugs e otimizações