Ajout du support système PlayStation®Vita TV
Ajout du support pour les nouveaux packs de DLC
Nouvelles évaluations d'amis où Dr. Psy vous compare à vos amis
Possibilité de voir les amis qui ont visité votre planète natale
Détection de mouvements améliorée
Correction d'un bug qui empêchait Robodachi de se débloquer
Meilleure synchronisation du son avec les bulles d'images
Correction de plusieurs autres bugs et optimisations diverses