Nye funktioner
- Korte versioner af sange er tilføjet
- Spiltypen Dyst i duet er tilføjet
- Rød vs. Blå – følg holdenes pointscore på spillelisten
- Gemmer topscorens spillernavn
Stabilitetsrettelser
- Forbindelsesforbedringer af SingStar Mic
- Optimering af SingStar Mic's ydelse og latenstid
- Forbedret synkronisering af sang og video i optagelser
- Ændringer af mikrofonens lydstyrke
- Generelle stabilitetsrettelser og mindre fejlrettelser