Nuevas funciones
- Modo Canción corta añadido
- Modo Batalla de dúos añadido
- Rojo contra Azul: utiliza la lista de reproducción para seguir la puntuación de los equipos
- Memorización del nombre del jugador con la puntuación máxima
Correcciones de estabilidad
- Mejoras de conectividad para SingStar Mic
- Optimización de rendimiento y reducción de latencia para SingStar Mic
- Corrección de la sincronización de voz y vídeo para el contenido multimedia tras la actuación
- Ajuste de los niveles de volumen del micrófono 
- Mejoras de estabilidad generales y corrección de errores menores