Novas funcionalidades
- Modo Canção de Duração Curta adicionado
- Modo Dueto de Combate adicionado 
- Vermelha vs. Azul - usa a Lista de Reprodução para seguires as pontuações das equipas
- Memorização do nome do jogador com pontuações mais altas
Correções de estabilidade
- Melhorias na ligação do SingStar Mic 
- Otimização do desempenho e redução de latência do SingStar Mic 
- Correção de sincronização de voz e vídeo para as atuações publicadas 
- Ajustes nos níveis de volume dos microfones 
- Melhorias gerais de estabilidade e correções de pequenos erros