・A bug preventing navigation voice selection in Options has been fixed.

[Warning when updating from a patch prior to Version 1.06]
In order to make room in the save data for bag names, the maximum number of skeletons
you can store at the temple has been decreased from 32 to 28. Skeletons stored in slots
29 and above will be deleted from your save data. Before updating to Patch 1.09, players
who have 29 or more skeletons are advised to please visit Canaan Temple where they can
either resurrect or bury excess skeletons to bring their total stock within 28.

Please refer to the official website for details.