This is a cumulative patch that adds new features and fixes some bugs.
WARNING:
    - All of the PlayStation®4, PlayStation®3, PlayStation®TV and PlayStation®Vita systems in a LAN game
    must have this patch applied in order to join the game
    - Daily Challenges recorded with an outdated version won't play

Features added:
    - Daily Challenge replays
    - New Fast Forward function for replays
    - Ghosts of dead friends in Daily Challenges

Bugs fixed:
    - Saved games could become corrupted under some circumstances
    - Some textures were being rendered incorrectly when using the quick start feature
    - Desynchronization issues in LAN games
    - Many other minor fixes and optimiztions
