<Ver 1.01>
Le seguenti funzioni sono state aggiunte al titolo:
- Quattro nuove tracce musicali.
- È ora possibile cambiare le musiche nel gioco
  online.
- Unendosi a un Gioco online, verranno visualizzati
  il livello di difficoltà e il numero di giocatori
  impostato dal reclutatore.
- Sono presenti dei fondi aggiuntivi per
  DYNASTY WARRIORS 7: Xtreme Legends.
- È ora possibile salvare gli indumenti nella galleria.
Gli errori seguenti sono stati risolti:
- Rari arresti anomali durante la visualizzazione degli
  Animali alleati nella Galleria dopo aver inserito
  determinati comandi.
- Rari arresti anomali dopo aver inserito determinati
  comandi con due armi assegnate della categoria
  Chakram.
- Rari arresti anomali durante l'esecuzione
  dell'Attacco Musou 2 di Zhang Jiao.
- Rari arresti anomali durante l'esecuzione
  dell'Attacco Musou 2 di Yuan Shao nel Gioco
  online.
- Mancata visualizzazione di determinati indumenti
  in battaglia.