<Versión 1.01>
Se han añadido las siguientes mejoras al juego:
- Cuatro nuevas canciones.
- Posibilidad de cambiar la música en el modo
  online.
- Cuando te unes a una partida online, ahora se
  muestra el nivel de dificultad y el número de
  jugadores configurados por el anfitrión.
- Hay fondos de pantalla adicionales para
  DYNASTY WARRIORS 7: Xtreme Legends.
- Los cambios realizados en los trajes en la galería
  ahora se pueden guardar.
Los siguientes fallos han sido corregidos:
- El juego se bloqueaba muy de vez en cuando al
  ver los animales guardianes en la galería después
  de haber pulsado ciertos controles.
- El juego se bloqueaba muy de vez en cuando
  después de haber pulsado ciertos controles si
  tenías equipadas dos armas de la categoría
  Ruletas.
- El juego se bloqueaba muy de vez en cuando al
  hacer un Ataque Musou 2 con Zhang Jiao.
- El juego se bloqueaba muy de vez en cuando al
  hacer un Ataque Musou 2 con Yuan Shao durante
  una partida online.
- Algunos trajes adicionales no se mostraban
  correctamente durante una batalla.