<Ver 1.01>
Die folgenden Neuerungen wurden dem Spiel
hinzugefügt:
- Vier neue Lieder.
- Die Möglichkeit in Online-Spielen die Musik zu
  wechseln.
- Beim Beitreten einer Online-Partie werden die
  vom Host festgelegte Schwierigkeitsstufe und
  Spieleranzahl angezeigt.
- Zusätzliche Hintergrundbilder für DYNASTY
  WARRIORS 7: Xtreme Legends werden angezeigt.
- Änderungen an Outfits in der Gallery (Galerie)
  können gespeichert werden.
Die folgenden Bugs wurden behoben:
- Das gelegentliche Einfrieren bei Ansicht der
  Wächtertiere in der Gallery (Galerie) nach
  Ausführung bestimmter Eingaben.
- Das gelegentliche Einfrieren nach Ausführung
  bestimmter Eingaben mit zwei Waffen der
  Kategorie "Wheels" (Räder).
- Das gelegentliche Einfrieren bei Ausführung von
  Zhang Jiaos Musou Attack (Musou-Angriff) 2.
- Das gelegentliche Einfrieren bei Ausführung von
  Yuan Shaos Musou Attack (Musou-Angriff) 2 bei
  Online-Spielen.
- Bestimmte zusätzliche Outfits werden in
  Schlachten nicht angezeigt.