Pääsy online-ominaisuuksiin on poistettu.
Voit jatkaa online-käyttöä SingStar®-pelin ilmaisversiolla,
joka on saatavilla XMB™-valikosta tai PlayStation®Store-verkkokaupasta.
Kaikki alla olevat ominaisuudet ovat valmiina käytettävissä SingStar™-pelin ilmaisversiossa:
- Pääsy SingStore™-verkkokauppaan
- Aiemmin ostetun sisällön (mukaan lukien lisäkappaleet) lataaminen
- Kuvien ja videoiden lähettäminen
- Lähetetyn aineiston katseleminen ja arvosteleminen
