Nouvelles fonctionnalités
- Mode Chanson Rapide ajouté
- Mode Combat en duo ajouté
- Rouge contre Bleu - utilise la playlist pour suivre les scores d'équipe
- Rappel des noms de joueur dans les Meilleurs scores
Correction des problèmes de stabilité
- Connection du SingStar Mic améliorée
- Optimisation des performances et diminution de la latence du SingStar Mic
- Correction de la synchronisation entre voix et vidéo dans les médias de performance publiés
- Ajustements du niveau de volume du microphone
- Amélioration de la stabilité et correction de bugs mineurs