Nieuwe functies
- Kort nummer-modus toegevoegd
- Strijdduetmodus toegevoegd
- Rood tegen Blauw - Volg de teamscores via de afspeellijst
- Topscore spelersnaam terughalen
Oplossingen betreffende stabiliteit
- Verbeteringen wat betreft verbinding met SingStar Mic
- Optimalisatie prestaties SingStar Mic en reductie van vertraging
- Problemen stem- en videosynchronisatie opgelost bij media na een optreden
- Aanpassing volumeniveaus microfoon
- Algemene verbeteringen wat betreft stabiliteit; kleine problemen opgelost