Nowe funkcje
 - Dodano tryb krótkiego utworu
 - Dodano tryb duetu bitewnego
 - Czerwoni kontra niebiescy - użyj listy utworów, aby śledzić wyniki drużyn
 - Wyświetlanie rekordów po imieniu gracza
Poprawki stabilności
 - Ulepszenie połączeń SingStar Mic
 - Optymalizacja wydajności i obniżenie opóźnienia SingStar Mic
 - Poprawa synchronizacji głosu i obrazu dla mediów po występie
 - Dostosowanie poziomów głośności mikrofonów
 - Ogólne poprawki stabilności i naprawa pomniejszych błędów