【Contenu de la mise à jour de la version 1.01】
・Ajout des fonctionnalités "Voir tout" et "Filtrer" dans la sélection d'armes
・Ajout de la possibilité de voir quels niveaux de difficulté d'un niveau ont été terminés en Mode Libre sur 
l'écran de résultats de bataille
・Il est désormais possible de sélectionner les armes uniques et secrètes lors de la fusion d'armes
・Il est désormais possible de réinitialiser les meilleurs records personnels dans le Mode Défi
・Dans le niveau "La Bataille du Château de Baidi", un bug qui faisait planter le jeu lorsque la baliste 
ennemie était détruite à partir du navire de transport a été corrigé
・Corrigé un bug qui empêchait les batailles de commencer lorsque l'officier de soutien était Cao Mao
・Corrigé un bug qui supprimait les données de DLC et faisait planter des niveaux lors de la présence de 
données de sauvegarde temporaire contenant un personnage portant une tenue de DLC
・Correction de bugs qui empêchaient de progresser dans certains niveaux
・Ajusté le nombre d'ennemis apparaissant dans les niveaux uniques au Mode Libre
・Correction de bugs supplémentaires et équilibrage du jeu