【Ver.1.01 Update-Inhalte】
・Der Waffenauswahl wurden Funktionen hinzugefügt, mit der alle Waffen angezeigt oder bestimmte Waffen 
gefiltert werden können
・Auf dem Auswahlbildschirm für das Schlachtfeld im Freien Modus können erfolgreich beendete Stages dem 
Schwierigkeitsgrad  nach angezeigt werden
・Die Optionen bei der Waffenfusion wurden erweitert, sodass auch geheime und einzigartige Waffen ausgewählt 
werden können
・Persönliche Bestleistungen können im Herausforderungsmodus zurückgesetzt werden
・In der Stage "Die Schlacht von Burg Baidi" stoppt das Spiel nicht mehr unvorhergesehen, wenn eine feindliche 
Balliste vom Transportschiff aus zerstört wird
・Ein Fehler, der verhinderte, dass der Kampf startet, wenn Cao Mao als unterstützender Offizier ausgewählt wurde, 
wurde behoben
・Ein Fehler, der DLC-Daten löschte und Stages beim Neustart zum Absturz brachte, wenn ein Zwischenspeicherstand 
vorlag, in dem ein Charakter ein DLC-Kostüm trägt, wurde behoben
・Fehler, die den Fortschritt in bestimmten Stages verhinderten, wurden behoben
・Die Anzahl der Feinde, die im Freier Modus erscheinen, wurde angepasst
・Weitere Änderungen, die die Spielbalance betreffen, und Behebungen von Fehlern