【Ver 1.01 Update Contents】
・The addition of "view all" and "filter" functions for weapon selection
・The addition of the ability to see which difficulty levels of a particular stage that you have cleared in 
Free Mode on the Battle Results Screen
・Options have been expanded when fusing weapons so that secret and unique weapons can also be selected
・The ability to reset personal bests in Challenge Mode
・In the stage “Battle of Baidi Castle,” a glitch that caused the game to freeze when destroying the 
enemy ballista from aboard the transport ship has been fixed
・A bug that prevented battles from starting when the supporting officer has been set to Cao Mao has been fixed
・A bug due to having interim save data where a character is wearing a DLC costume that caused DLC data to be 
deleted and stages to crash when restarted has been fixed
・Bugs that prevented progress in certain stages have been fixed
・The adjustment of the number of enemies that appear in Free Mode only stages
・Additional game balance adjustments and bug fixes