- DLC-Unterstützung.

- Ein neuer Schwierigkeitsgrad <STURMANGRIFF> wurde hinzugefügt.
  Dieser neue Modus erscheint automatisch, sobald der
  Schwierigkeitsgrad <SEHR SCHWER> freigespielt worden ist.

- Erweiterung des Wiedergabemodus. Durch das Betätigen der
  R1-Taste lässt sich eine Welt überspringen. Diese Funktion
  ist in der letzten Welt der Wiedergabe nicht verfügbar.

- Weitere geringfügige Verbesserungen.

- Behebung einiger geringer Fehler. 