L'accès aux fonctions en ligne a été supprimé.
Rejoins-nous en ligne avec la version gratuite de SingStar®
disponible depuis le menu XMB™ ou PlayStation®Store.
Les fonctions ci-dessous sont déjà disponibles dans la version gratuite de SingStar™ :
- Accès au SingStore™
- Téléchargement des contenus achetés précédemment (dont les packs de chansons)
- Envoi des captures d'écran et des vidéos
- Affichage et notation des médias envoyés
