Hinweise:
- Gespeicherte Daten, die vor dieser Aktualisierung erstellt wurden,
können nicht verwendet werden, um Trophäen zu gewinnen
- Gespeicherte Daten, die nach dieser Aktualisierung erstellt wurden,
können nicht als vor der Aktualisierung gespeicherte Daten verwendet werden

Änderungen:
- Trophäen hinzugefügt
- Komplettinstallation als neue Funktion hinzugefügt
- METAL GEAR ONLINE Menüeinträge und Daten gelöscht, da der Service eingestellt wurde
