Tillgång till onlinefunktioner har tagits bort.
Fortsätt att vara med oss online med gratisversionen av SingStar® 
som finns tillgänglig i XMB™-menyn och PlayStation®Store. 
Alla nedanstående funktioner från skivversioner av spelet finns redan tillgängliga i gratisversionen av SingStar™:
- Tillgång till SingStore™
- Nedladdning av tidigare köpt innehåll (inklusive låttillägg)
- Uppladdning av foton och videoinspelningar
- Visning och betygsättning av uppladdade media