O acesso a funcionalidades online foi removido.
Continua a juntar-te a nós online através da versão gratuita do SingStar®, 
disponível no Menu XMB™ ou na PlayStation®Store. 
As seguintes funcionalidades de disco já se encontram disponíveis através da versão gratuita do SingStar™:
- Acesso à SingStore™
- Transferência de conteúdos comprados anteriormente (incluindo add-ons de canções)
- Envio de fotografias e reproduções de vídeos
- Visualização e classificação de media enviados