Access to online features has been removed.
Continue to join us online in the free version of SingStar™
that is available on the XMB™ Menu or PlayStation®Store.  
All of the below disc features are already available via the free version of SingStar™
- Access to the SingStore™
- Download of previously purchased content (including song add-ons)
- Uploading of snapshots and video playback
- Viewing and rating of uploaded media