Se ha eliminado el acceso a las funciones online.
Continúa uniéndote a nosotros online en la versión sin coste alguno de SingStar® 
disponible en el menú XMB™ (XrossMediaBar) o en PlayStation®Store. 
Todas las funciones de disco de abajo ya están disponibles en la versión sin coste alguno de SingStar®:
- Acceso a SingStore®
- Descarga de contenido adquirido previamente (incluyendo funciones de canciones)
- Carga de fotografías y reproducciones de vídeo
- Visionado y calificación de medios cargados