De toegang tot online-functies is verwijderd.
Je kunt online met ons doorgaan in de gratis versie van SingStar® 
die beschikbaar is in het XMB™-menu of de PlayStation®Store. 
De volgende disc-functies zijn al beschikbaar via de gratis versie van SingStar®:
- Toegang tot de SingStore®
- Download van eerder gekochte inhoud (inclusief extra nummers)
- Uploaden van foto's en beeldopnamen
- Bekijken en beoordelen van geüploade media