Rimosso l'accesso alle funzioni online. 
Continuate a giocare online con la versione gratuita di SingStar® 
accedendo dal menu XMB™ o da PlayStation®Store. 
Tutti i contenuti del disco elencati qui di seguito sono già disponibili nella versione gratuita di SingStar™:
- Accesso a SingStore™
- Download dei contenuti già acquistati (inclusi i brani aggiuntivi)
- Caricamento di istantanee e playback video
- Visualizzazione e valutazione dei media caricati