O acesso aos recursos online foi removido.
Continue a entrar online na versão gratuita de SingStar®, 
disponível no menu XMB™ ou na PlayStation®Store. 
Todos os recursos do disco abaixo já estão disponíveis na versão gratuita do SingStar™:
- Acesso à SingStore™
- Baixar conteúdo adquirido previamente (incluindo complementos de músicas)
- Envio de instantâneos e reproduções de vídeo
- Visualização e classificação de mídia enviada