Adgang til onlinefunktioner er fjernet. 
Du kan stadig slutte dig til os online i den gratis version af SingStar®, 
der er tilgængelig i XMB™-menuen eller PlayStation®Store. 
Alle de diskfunktioner, der beskrives nedenfor, er allerede tilgængelige i den gratis version af SingStar™:
- Adgang til SingStore™
- Download af indhold, du tidligere har købt (inklusive sangtilføjelser)
- Upload af snapshots og videoafspilninger
- Visning og vurdering af uploadede medier