Uudet ominaisuudet
- Lisätty lyhyen laulun tila
- Lisätty duettokamppailutila
- Punainen vs. sininen, soittolistojen käyttö joukkueen pisteiden seurantaan
- Huippupisteiden pelaajan nimen haku
Vakauteen vaikuttavia korjauksia
- SingStar Mic -yhteysparannuksia
- SingStar Mic -suorituskykyoptimointeja ja viiveiden pienennyksiä
- Ääni- ja videosynkronoinnin korjaus esityksen jälkeiselle medialle
- Mikrofonin äänenvoimakkuustason säätöjä 
- Yleisiä vakausparannuksia ja pieniä virheenkorjauksia