New Features
- Short Song Mode added
- Battle Duet Mode added
- Red VS. Blue - use Playlist to track team scores
- High score player name recall
Stability Fixes
- SingStar Mic connection improvements
- SingStar Mic performance optimisation and latency reduction
- Voice and video synchronisation fix for post performance media
- Adjustment to microphone volume levels 
- General stability improvements and minor bug fixes