Neue Funktionen
- "Kurzer Song"-Modus hinzugefügt
- Battle-Duett-Modus hinzugefügt
- Rot gegen Blau – Teampunkte über die Wiedergabeliste verfolgen
- Abrufen der Spielernamen mit den höchsten Punktzahlen
Stabilitätsverbesserungen
- Verbesserung bei der Verbindung mit SingStar Mic
- Leistungsoptimierung von SingStar Mic und Latenzreduzierung
- Behebung des Problems bei Video- und Stimm-Synchronisation für Medien nach dem Auftritt
- Anpassung der Mikrofonlautstärkepegel
- Allgemeine Stabilitätsverbesserungen und kleinere Fehlerbehebungen