<Version 1.02>
Les fonctionnalités et éléments suivants ont été
ajoutés au jeu :
- Quatre nouvelles pistes musicales.
- La possibilité de changer la musique lors d'une
  partie en ligne.
- L'affichage du niveau de difficulté et du nombre de
  joueurs désignés par l'hébergeur des parties en
  ligne que vous souhaitez rejoindre.
- La mise à disposition de fonds d'écran
  supplémentaires DYNASTY WARRIORS 7: Xtreme
  Legends.
- La possibilité de sauvegarder les changements de
  tenues effectués dans la galerie.
Les bugs suivants ont été corrigés :
- Le jeu avait tendance à se figer lorsque le joueur
  consultait les animaux gardiens dans la galerie
  après avoir réalisé certaines commandes.
- Le jeu avait tendance à se figer lorsque le joueur
  réalisait certaines commandes en étant équipé de
  deux armes de la catégorie des disques-lames.
- Le jeu avait tendance à se figer lorsque le joueur
  réalisait l'attaque Musou de Zhang Jiao de
  niveau 2.
- Le jeu avait tendance à se figer lorsque le joueur
  réalisait l'attaque Musou de Yuan Shao de
  niveau 2 lors d'une partie en ligne.
- Certaines tenues supplémentaires ne s'affichaient
  pas correctement dans les combats.