<Ver 1.02>
The following features have been added to the title:
- Four new music tracks.
- The ability to change the music in Online Play.
- When joining an Online Play match, the difficulty
  level and number of players set by the recruiter
  are displayed.
- Additional wallpapers for DYNASTY WARRIORS 7:
  Xtreme Legends are displayed.
- Changes made to outfits in the Gallery can be
  saved.
The following bugs have been fixed:
- The game would very occasionally freeze upon
  viewing the Guardian Animals in the Gallery after
  having inputted certain controls.
- The game would very occasionally freeze after
  inputting certain controls with two weapons from
  the Wheels category equipped.
- The game would very occasionally freeze upon
  performing Zhang Jiao's Musou Attack 2.
- The game would very occasionally freeze upon
  performing Yuan Shao's Musou Attack 2 in Online
  Play.
- Certain additional outfits would not be displayed
  in battle.