Fixed spanish translation of DOWNLOAD SAVE GAME
Disallow game clip sharing if chat restrictions are in place
Fixed beeps when quitting during sign in dialog
Removed santamatch from single player and coop multiplayer
Fixed icons in leaderboards regarding gameclips
Fixed hang when accepting inviting while in your own multiplayer lobby
Fixed gameclip uploading for dukematches
Fixed scoring for dukematch leaderboards and ranked kills achievements
Fixed overall and own score leaderboards display