Patch 1

Prevent the box or the player to get stuck/sink into walls and items when picking up objects.
Prevent shadow shifting at start of game except on a specific wall onto which we want to teach the user to shift into shadow.
Fix Boxgetting stuck in walls on exit.
Fix Box landing and staying on Player Head
Fix Box landing on Moving actors and floating into space. 
Don't allow the player to shift into Blocking Volumes.
Don't allow the player to go into Blocking Volumes while in shadows (and get stuck).
Don't allow the player to go through walls while shifted in shadows.
Display the walking animation when stuck in a stable configuration while falling.
Allow jumping in that case to help the player get out of the collision.
Fix getting stuck while shifting out.
Fix going through walls and stop dash from going through shadows.
Fix for the box falling on the player's head and floating in space.
Fix Carousel loading / persistent problem
