*The ultimate 3D dot hessian sack hero, Sackboy™, arrives in your gallery to save Dotnia Kingdom!
 Courtesy of Sony Computer Entertainment Europe.

*New character models created by and for the fans have been added!
 A special thank you to all the dot designers who contributed!

*Motti has begrudgingly admitted that Dash Race was too hard.
 The required completion times have been adjusted.

*Certain swords will now carry over in New Game+.
 It was too dangerous to go alone.

*Are there some holes in your Loading Art gallery?
 Specifically, images #70 through #105? Sorry about that!
 The art will now appear randomly, and upon being viewed, be displayed in the gallery.
 (The Loading Art option must be turned ON.)
