- Intégration du support pour contenu téléchargeable.

- Ajout d'un nouveau mode de difficulté <INFERNAL>. Ce mode
  de difficulté est débloqué en même temps que le mode 
  <TRÈS DIFFICILE>. 

- Ajout d'une fonction 'PASSER' pour le mode replay. Appuyez
  sur R1 pour passer au niveau suivant. Cette fonctionnalité
  n'est pas disponible au dernier niveau du replay!

- Diverses améliorations mineures effectuées.

- Adressage de quelques problèmes mineurs.