Fonctions supplémentaires

Ce titre est désormais compatible avec la lecture à distance sur le système PlayStation®Vita.
Pour plus de détails, veuillez visiter le site officiel PlayStation® (http://www.playstation.com/).

※ Le système PSP™ (PlayStation®Portable) n'est pas compatible avec la lecture à distance.


« PlayStation » est une marque déposée et « PSP » est une marque de Sony Computer Entertainment Inc.