Die Zugangsberechtigung zu den Online-Funktionen wurde entfernt.
Bleibe mit der kostenlosen Version von SingStar®,
verfügbar im XMB™ (XrossMediaBar)-Menü oder in PlayStation®Store, weiterhin online an unserer Seite.
Alle der unten genannten Punkte sind bereits mit der kostenlosen Version von SingStar™ verfügbar:
- Zugang zum SingStore™
- Herunterladen zuvor gekaufter Inhalte (auch Song-Erweiterungen)
- Hochladen von Schnappschüssen und Video-Wiederholungen
- Ansehen und Bewerten hochgeladener Medien
