Ragnarok Odyssey ACE
Ver 1.11

Updating Information
  ・Addition of "Jester Hat" and "Patrol Lights" headgear

[Fixes to Bugs]
  ・Fixed an issue regarding the intended amount of Prismatic Dust being dropped by the Domovoi Ranger enemy.
  ・Adjusted the functionality of the L2 button in Control Types 2 and 4; Lock-On now gets canceled by releasing the L2 button.
  ・Various other bugs have been fixed.

