- A new BEGINNER difficulty level has been added, specifically for
all the players who requested a very easy beginner's mode.
Please note: Once you have saved your save-game with the patched version,
you can not re-load this with the original version any longer!

- A new tutorial has been added. It will be triggered after dying for the
first time in world #2 or later. The tutorial explains how to avoid getting
stuck within obstacles.

- The outro and credit cutscenes can now be skipped. However, skipping is
only possible after watching the credits at least one time until the end.

- On very rare occassions, a bug occured during a boss fight, forcing the
player to quit and restart the game. This has been fixed.

- Several minor improvements have been made.
