- Version 1.10:
  
NEW FEATURES:
- A new zero star battle rank has been added. Battles will be much easier for players that 
  just want to focus on story and exploration parts.

- Battle skill animations can now be skipped right from the start. The following options have
  been added:
  - <Default> This is the old default behavior.
  - <Skip always> All skills can always be skipped by holding down the R2 button.
    This also affects monster skills.
  - <Auto skip> All animations are skipped automatically without holding down the R2 button.
    If a new skill is discovered, it will be displayed once, but all follow up animations of the
    same skill are skipped. This affects ally and enemy skills.

IMPROVEMENTS:
- Several help notifications have been added.
  - These notifications only appear in the beginning of the game.
  - A help notification will be displayed in case certain key features of the game are not used,
    such as:
    - many skill stones have been collected but not spent in the upgrade menu.
    - new skill books have not been purchased and studied in a while.
    - new gear has not been purchased, although sufficient coins are available.
    - equipment has not been improved at the blacksmith with collected materials.
    - a reminder that players can switch to the battle menu by pressing the cancel button.
- All vehicles can now also be entered by pressing the SELECT button when standing close to the
  vehicle. This prevents very rare situations where players were no longer able to enter their
  vehicle after landing in very small areas with other interactive objects nearby.
    
BUGFIXES:
- Fixed an issue where the main character did not reappear after changing equipment in very
  populated spots.
- The passive skill "Kamikaze" now works properly in all situations and the damage prediction
  always matches the expected result.
- Fixed an issue where the HP display could become corrupted when fighting an end game boss on
  battle rank 9.
- Fixed a very rare issue that allowed battles with notorious monsters to be initiated while they
  were despawning.
- Fixed an issue at the monster farm that allowed players to change the egg selection while the
  rename requester was spawned. This could lead to the removal of the wrong egg and other side
  effects.
- Fixed several bugs related to the monster house. In case corrupted units are stored in the
  monster house, they will automatically be repaired when loading the save data.
- If a battle was started, while the lottery music was played, the battle music was not played
  at all.
- Fixed a crash that could occur after a trial battle if the speech bubble was not confirmed
  immediately.
- Fixed a bug that could lead to triggering empty battles in the end game dungeon "Cascades of
  Mystery."
- A bag in the "Glimmer Mine" could not be collected if a big character or monster was selected
  as leader.
- Fixed several text typos.
- Other minor or cosmetic improvements and fixes.
