Increased the amount of auto-turning when the surfer is facing up the wave, so that they get turned to go back down the wave.
Added in the ability to press X during a wipeout sequence to skip through it. The underwater wipeout cutscene can now be
skipped allowing for faster play.
Removed the whitewater particles from the ends of the waves in Fernando’s Cove.
Reduced the amount of time before the surfer wipes out when they are in stall and are facing up the wave.
Introduced multilingual warning message screens for the Monsters location and levels. The game detects whether the right
boards are being used and displays a “big-wave” warning message if they are using the wrong boards. Improved character stats
for big waves are also recommended. This is because performance is hampered for players if the incorrect equipment is selected
for very large waves.
