Update-Informationen zu Ver. 1.02
 - Im Optionsmenü unter “Speichern/Laden” können nun Spielstände hochgeladen werden
 - Die Musik für eine Stage kann nun zufällig ausgewählt werden
 - Ein Fehler, bei dem das Wegwerfen eines Tieres in einem Online-Spiel zum Einfrieren des Spiels führte, wurde behoben
 - Fehler bezüglich Stages, die nicht abgeschlossen werden konnten, wurden behoben
 - Andere Fehler wurden behoben
