MEO VIDEOCLUBE

MEO VideoClube allows you to watch thousands of movies anywhere and on every device: on your TV through the MEOBox, on your Samsung Smart TV, Sony Playstation 3 and tablet, smartphone and PC with MEO Go.
Use the Download & Play feature to watch your favorite movies on your PC without needing an internet connection. Go to meogo.pt to learn more.

MEO VIDEOCLUBE MOVIES

Rent the most exciting blockbusters from Hollywood and watch them as many times as you want in a 48 hour period.
You can also experiment the best movie quality with our High-Definition movie selection.
Check all the available movies in meogo.pt.

PAYMENT METHODS

The MEO VideoClube service allows you to pay the rented movies through direct debit in your PT monthly bill or with the pre-paid card MEO VideoClube Card. Go to meogo.pt to learn more.
If you want you can request a detailed list in your monthly bill with all the movies you rented.

PARENTAL CONTROL

You can define a PIN to manage the movie rentals. This PIN will be prompted each time a rental is made.