[Version 3.00 Update Notes]

* WARNING:
  Save data created in v3.00 is not playable in prior versions of the game.
  You may continue to use save data created in versions prior to v3.00,
  but it is recommended that you create a new save file instead of
  overwriting existing data the first time you save a game in v3.00.

- An "Easy Mode" has been added to make battles easier.
  You will be prompted to select a difficulty level when choosing "New Game" from the title screen,
  or alternatively, you can change the difficulty level during play from the main menu's
  "Game Settings" option.
- New Imajinn tickets have been added for "NI NO KUNI: DAIBOUKEN MONSTERS" (English name TBD).
  Speak to the Imajinnn Manhole rep. to receive your Imajinn tickets.
- A new sort feature has been added to the Imajinn Manhole.
- You are now able to toggle on/off the map's guiding star that directs you to your next goal
  via the main menu's "Game Settings" option.
- Other misc. gameplay fixes and tweaks.
