Version 1.40 Patch Notes

[Bug Fixes]
- Fixed the freeze that occurred during skill animations.
- Fixed the window size of a warning message that pops up when the install data is corrupted.
- Fixed the activation of certain conversation flags after creating the maximum number of characters.
- Fixed the issue where Laharl's (Prinny's, during Prinny Day) HP becomes 1 when a stage is cleared
   while there are no more characters to dispatch in the Base Panel.
- Fixed the issue of the wrong voice playing when Marona uses her Confine skill with the English voices selected.
- Fixed audio issues during the Dark Assembly and Item Assembly.