Ver. 1.01
Important Notice
When using a version of "DYNASTY WARRIORS 7 Empires" for which this update has not been applied (Ver. 1.00),
 please refrain from loading play data or system data that was created after applying this update.
 (Save data that was created before applying the update can be used without issue even after applying the update.)

The following features were added:
 - Test Battle was added to Edit Mode.
  (Stratagems can be used for testing, but Plots cannot be selected.)
 - The number of colors that can be selected for hair in Edit Mode has been expanded to 256.
 - Strengthened the influence of play histories recorded by created officers.
  (The content of play history data is not changed from that of Ver. 1.00.)
 - The following options have been added to the initial settings for Empire Mode:
  (The options can be used after clearing Empire Mode.)
   - Randomization of NPC default Fame.
   - Basic Fame level for created NPC officers.
 - Added the Strategy command "Depart".
 (The command can only be used when you are affiliated with a force as a subordinate. Rulers cannot use it.)
 - The progress of missions is now displayed in the mission info of the Strategy screen.
 - For NPC forces, the NPC's that take on positions such as Strategists and Marshals will now change.
 - When switching the camera at your Abode, the camera's previous position will now be remembered.
 - Added functionality to the L2 button to enable players to give orders to their entire force during battle.
  (This can only be used in situations for which the command "Give Orders" can be used.)
 - Added General Order to the "Give Orders" command on the Information Screen during battle.
 - Reduced the possibility of sworn siblings and spouses becoming a commander during battle.
 - Adjusted the amount that attack power is raised for the Stratagems "Immovable" and "Peerless".
 - "Meat Buns" now appear when defeating enemies during Surprise Attacks.
 - Increased the number of events in which allied NPC officers speak lines.
 - When captured officers are released, they will now return to their former forces if possible.
 - Adjusted conversations that occur as a result of Friendship levels.
The following issues were corrected:
 - Corrected an issue in which under certain conditions the game would stop or could not be advanced during the Strategy Phase
 - Corrected an issue in which under certain conditions the game would stop during battle.
 - Corrected an issue in which the faces of officers were not displayed for conversations during the Strategy Phase.
 - Corrected an issue in which ability values were incorrectly increased when using "Unlock Items".
 - Corrected an issue in which, when the player received weapon attacks that latch onto the player,
    such as standard great axe attacks, such weapons were not displayed correctly.
 - Corrected a number of other graphical issues.
