Novos recursos
- Modo de Canção Curta adicionado
- Modo de Dueto de Batalha adicionado
- Vermelho vs. Azul - use a Lista de reprodução para acompanhar as pontuações das equipes
- Memorização do nome do jogador com pontuações mais altas
Correções de estabilidade
- Melhorias de conexão do SingStar Mic
- Otimização de desempenho e redução de latência do SingStar Mic
- Correção de sincronização de voz e vídeo para mídia pós-apresentação
- Ajuste nos níveis de volume do microfone
- Melhorias gerais de estabilidade e correções de bugs menores