[Ver.1.03 Update Description]

* The following feature has been added:
- The high difficulty level scenario "Persistence Pays Off."

* The following general improvement has been made:
- Pop-up during online play has been ameliorated. 

* The following bugs have been addressed:
- A certain combination of inputs at the officer selection screen before the Empire Mode scenario,
  "A Gathering of Heroes," results in the game freezing. 
- Repeating army commands results in some officers not appearing. 
- Certain other minor issues. 
