Détails de la mise à jour ver. 1.02
 - La possibilité de mettre en ligne des données de sauvegarde a été ajoutée dans « Sauvegarder/Charger » dans le menu Options
 - La possibilité de choisir une musique de niveau aléatoirement a été ajoutée
 - Un bug faisant planter le jeu après avoir jeté un animal lors d'une partie en ligne a été corrigé
 - Des bugs relatifs à certains niveaux ne pouvant être terminés ont été corrigés
 - D'autres bugs ont été corrigés
