Nytt innhold
- Kort sang-modus lagt til
- Kampduett-modus lagt til
- Rød mot blå – få oversikt over lagresultater på spillelisten
- Navnet til spilleren med det beste resultatet huskes
Stabilitetsforbedringer
- Bedre forbindelse for SingStar Mic
- Bedre ytelse og mindre forsinkelse for SingStar Mic
- Feilretting av synkronisering mellom stemme og video for medieinnhold etter opptredener
- Justering av lydnivå på mikrofoner
- Feilretting og generell forbedring av stabilitet