Nuove caratteristiche
- Aggiunta la modalità Canzone breve
- Aggiunta la modalità Duetto battaglia
- Rossi contro Blu: usa la Playlist per tenere traccia dei punteggi di squadra
- Registra il nome del giocatore con punteggio più alto
Risoluzione problemi di stabilità
- Migliorata la connessione di SingStar Mic
- Ottimizzate le prestazioni di SingStar Mic e ridotta la latenza
- Corretta la sincronizzazione di voce e video dei media dopo l'esibizione
- Regolati i livelli del volume del microfono
- Migliorata la stabilità generale e corretti alcuni bug minori