Nya funktioner
- Nyhet: kort låtläge
- Nyhet: duellduett
- Röda mot blå - håll koll på lagpoäng i spellistan
- Hågkomst av spelarnamn vid rekord

Stabilitetsförbättringar
- Förbättrad anslutning för SingStar Mic
- Prestandaoptimering och latensminimering för SingStar Mic
- Röst- och videosynkronisering justerad i framträdandemedia
- Justering av volymnivåer för mikrofoner
- Allmänna stabilitetsförbättringar och små buggfixar