Dostęp do funkcji sieciowych został wyłączony.
Dołącz do nas w sieci w bezpłatnej wersji SingStar®,
dostępnej w menu XMB lub PlayStation®Store.
Wszystkie poniższe funkcje dyskowe są już dostępne w bezpłatnej wersji SingStar™:
- Dostęp do SingStore™
- Pobieranie uprzednio zakupionej zawartości (w tym piosenek dodatkowych)
- Przesyłanie zdjęć i klipów
- Wyświetlanie i ocenianie przesłanych materiałów
